[project]
name = "toursandtravels"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "vijay singh", email = "rajputvijaysingh@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "cloudinary>=1.44.0",
    "bcrypt>=4.0.1,<4.1",
    "fastapi>=0.115.0",
    "passlib[bcrypt]>=1.7.4",
    "pydantic[email]>=2.9.0",
    "pyjwt>=2.9.0",
    "pymongo>=4.9.0",
    "python-dotenv>=1.0.1",
    "python-multipart>=0.0.20",
    "uvicorn>=0.30.0",
]

[project.scripts]
toursandtravels = "toursandtravels:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
